"""
Django settings for mysite project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
=======
Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'so_hymlkd!(n6-&1!zwkiu(ro+3x580a3!^s-l_*$-6()w_f2('
=======
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n&a%cr4k%!)d2v42j6izh^&#y$=7yi5!1z68ekz!wssu@oq2&u'
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
<<<<<<< HEAD
    # 'django.middleware.csrf.CsrfViewMiddleware',
=======
    'django.middleware.csrf.CsrfViewMiddleware',
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [os.path.join(BASE_DIR,  'templates'), ],
=======
        'DIRS': [os.path.join(BASE_DIR, "template")],
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.10/topics/i18n/
=======
# https://docs.djangoproject.com/en/1.11/topics/i18n/
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
=======
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
>>>>>>> 4d8e22026e5388c256224a40b4173f3ca4f93392
