# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(related_name='_author_friends_+', to='app01.Author'),
        ),
    ]
