# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='memo',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
