# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_auto_20180124_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Publisher'),
        ),
    ]
