# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='app02.Class')),
            ],
        ),
    ]
