# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_auto_20180122_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='first_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
