# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
