# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 08:41
from __future__ import unicode_literals

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0002_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('cname', app01.models.FixedCharField(max_length=25)),
            ],
        ),
    ]
