# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('first_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher2Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Teacher')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Class')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='cid',
            field=models.ManyToManyField(through='app03.Teacher2Class', to='app03.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher2class',
            unique_together=set([('teacher', 'the_class')]),
        ),
    ]
