# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Class')),
            ],
        ),
    ]
