# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(unique=True)),
                ('md5', models.CharField(max_length=32)),
                ('memo', models.TextField(max_length=128)),
            ],
        ),
    ]
