# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='date',
            new_name='first_day',
        ),
    ]
