# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='上线时间')),
                ('name', models.CharField(max_length=32, verbose_name='产品')),
                ('status', models.IntegerField(verbose_name='状态')),
            ],
        ),
    ]
