# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.IntegerField(choices=[(0, '在计划'), (1, '已上线'), (-1, '下线了')], verbose_name='状态'),
        ),
    ]
