# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170723_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, '计划中'), (1, '已上线'), (-1, '下线了')], verbose_name='状态'),
        ),
    ]
