# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCountries',
            fields=[
                ('country_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='出口国编码')),
                ('country_name', models.CharField(max_length=128, verbose_name='出口国名称')),
            ],
            options={
                'verbose_name_plural': '出口国表',
                'verbose_name': '出口国表',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='商品编码')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='单价')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '商品表',
                'verbose_name': '商品表',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='报表编号')),
                ('data', models.DateField(verbose_name='销售日期')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.ExportCountries', verbose_name='出口国编码')),
            ],
            options={
                'verbose_name_plural': '销售表',
                'verbose_name': '销售表',
            },
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Products', verbose_name='商品编码')),
                ('sale_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Sales', verbose_name='报表编码')),
            ],
            options={
                'verbose_name_plural': '销售明细表',
                'verbose_name': '销售明细表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='salesinfo',
            unique_together=set([('sale_code', 'product_code')]),
        ),
    ]
