# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default='2017-08-27', verbose_name='时间'),
            preserve_default=False,
        ),
    ]
