# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书', 'verbose_name_plural': '书'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=0, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=32, verbose_name='出版社名称'),
        ),
    ]
