# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=64, null=True, verbose_name='权限URL')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='权限标题')),
                ('tag', models.IntegerField(choices=[(1, 'add'), (2, 'sel'), (3, 'edi'), (4, 'del')])),
                ('is_title', models.BooleanField(verbose_name='是不是菜单')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色名')),
                ('auths', models.ManyToManyField(to='app03.Auth')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='密码')),
                ('Ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='人名')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
                ('roles', models.ManyToManyField(to='app03.Role')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
