# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名')),
                ('task_desc', models.TextField(verbose_name='任务详情')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
