# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20161227_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_author_friends_+', to='app01.Author'),
        ),
    ]
