# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20161229_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='days',
            field=models.IntegerField(default=200, verbose_name='写作耗时'),
        ),
    ]
