# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_book_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='publisherID',
        ),
    ]
