# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20170210_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('publisher', models.ManyToManyField(to='app01.Publisher')),
            ],
        ),
    ]
