# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='经纪公司名')),
                ('address', models.CharField(max_length=32, verbose_name='公司地址')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='company',
            field=models.ForeignKey(blank=True, help_text='签约的经纪公司', null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Company'),
        ),
    ]
