# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20170215_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Group'),
        ),
    ]
