# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20170225_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Group'),
            preserve_default=False,
        ),
    ]
