# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherToClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app04.Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app04.Teacher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teachertoclass',
            unique_together=set([('teacher', 'class_info')]),
        ),
    ]
