# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='first_day',
            field=models.DateField(null=True),
        ),
    ]
